apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: eltincho89/argo-poc-x11:3.0
        name: test
        ports:
        - containerPort: 80
