apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
    spec:
      containers:
      - image: eltincho89/argo-poc-x11:2.0
        name: test2
        ports:
        - containerPort: 80
